projectsInfo=[
{
	"picName":"project1",
	"info":"北京邮电大学运动会管理系统",
	"detail":"北京邮电大学体育部运动会管理系统，包括拥有不同权限的角色（管理员、主副裁判、领队老师、运动员等）对各自信息的查询、管理。页面全部由前端渲染，充分利用jQuery框架及Ajax等技术。",
	"url":"http://ped.bupt.edu.cn/BuptComp/none/index.do"
},
{
	"picName":"project2",
	"info":"湖南海事局会议室预定系统",
	"detail":"湖南海事局会议室预定系统，提供对该局所有会议室信息的读取显示、会议室预定、预订信息查询、会议资料上传下载等功能。",
	"url":"http://xiaotianxia.github.io/imdaizhen/meetReservationSys/"
},
{
	"picName":"project3",
	"info":"大连海事大学王新年教授个人主页",
	"detail":"大连海事大学王新年教授个人主页，页面大部分数据、图片及表格全部通过js解析json数据生成，便于后期编辑及修改。",
	"url":"http://sipi.dlmu.edu.cn/wxn.html"
},
{
	"picName":"project4",
	"info":"ICSINC国际会议官方网站",
	"detail":"ICSINC（International Conference on Signal Processing on Information, Network and Computer）官方网站。主要是一些静态页面、列表、图片的展示。",
	"url":"http://xiaotianxia.github.io/imdaizhen/ICSINC/"
},
{
	"picName":"",
	"info":"端到端安全防护系统",
	"detail":"端到端安全防护系统，包括对网络业务的安全分析，建立起QoP评价规则，对网络进行安全评估；实现部分包括搭建演示环境及QoP评价系统，实现对网络的安全评估和管理。我负责数据可视化的显示部分，主要利用D3.js实现的有向线段之间的箭头的显示。",
	"url":"#"
},
{
	"picName":"project6",
	"info":"全国养老需求服务评估系统 ",
	"detail":"该系统收集全国纳入养老范围的老年人的信息，评估师通过该系统对老年人发出的养老评估申请进行评估，以确定该老人所能享受的福利等级，政府也可通过该系统对各种数据进行了解。主要参与部分静态网页的开发及页面UI的设计。",
	"url":"#"
}
]